[paths]
raw = 'datasets/raw'
processed = 'datasets/processed'
plots = 'plots'

[project_data]
project_name = 'MAPHIS'
city_names = ['Luton']

[operations]
[operations.pre_processing]
### Information about the maps
# map_image_file_extension (str): file extension of the map image data (e.g: '.tif')
# map_geodata_file_extension (str): file extension of the map projection data (e.g: '.tfw')
map_image_file_extension = '.tif'
### Information about geospatial data in the project
# crs : Coordinate REference System (e.g: "EPSG:4326")
# geo_data_file_extension : file extension to which save the geospatial data to (e.g: '.geojson'); see: https://geopandas.org/en/stable/docs/user_guide/io.html
# geo_data_file_extension_driver = driver to save the geospatial data (e.g: 'GeoJSON'); see: https://geopandas.org/en/stable/docs/user_guide/io.html
geo_data_file_extension = '.shp'
geo_data_file_extension_driver = 'ESRI Shapefile'

### process
[operations.extract_features]
[operations.extract_features.essentials]
### Essential regardless Operation
geo_data_file_extension = '.shp'
geo_data_file_extension_driver = 'ESRI Shapefile'
[[operations.extract_features.processes]]
process_name = 'ml_segmentation'
feature_names = ['buildings', 'text', 'vegetation']
city_overwrite = true
tile_overwrite = true
[operations.extract_features.processes.data_feeding_dict]
batch_size = 8
shuffle = true
num_workers = 1
tile_transform = 'maphis_transform'
thumbnail_transforms = [
    ['ToFloat'], ['Normalise']
    ]
[operations.extract_features.processes.model_dict]
name = 'maphis_segmentation'
load_path = 'datasets/models/MAPHIS/segmentation/segmentation_real_state_dict.pth'
train_mode = false
ngf = 4
n_gabor_filters = 64
support_sizes = [5, 7, 9, 11]
n_input_channels = 3
n_output_channels = 4
device = 'cuda:0'
