[paths]
raw = 'datasets/raw'
processed = 'datasets/processed'
plots = 'plots'

[project_data]
project_name = 'MAPHIS'
city_names = ['Luton']

[operations]
[operations.pre_processing]
### Information about the maps
# map_image_file_extension (str): file extension of the map image data (e.g: '.tif')
# map_geodata_file_extension (str): file extension of the map projection data (e.g: '.tfw')
map_image_file_extension = '.tif'
### Information about geospatial data in the project
# crs : Coordinate REference System (e.g: "EPSG:4326")
# geo_data_file_extension : file extension to which save the geospatial data to (e.g: '.geojson'); see: https://geopandas.org/en/stable/docs/user_guide/io.html
# geo_data_file_extension_driver = driver to save the geospatial data (e.g: 'GeoJSON'); see: https://geopandas.org/en/stable/docs/user_guide/io.html
geo_data_file_extension = '.geojson' #'.shp
geo_data_file_extension_driver = 'GeoJSON' # 'ESRI Shapefile'

### process
[operations.extract_features]
[operations.extract_features.essentials]
### Essential regardless Operation
geo_data_file_extension = '.geojson'
geo_data_file_extension_driver = 'GeoJSON'
[[operations.extract_features.processes]]
process_name = 'hand_labelled_feature_extraction'
feature_names = ['buildings', 'text', 'vegetation']
color_thresholds = [77, 179, 167]
label_file_extension = '.jpg'
epsilon = 0.001
area_detection_threshold = 530
path_to_hand_segmented_features = 'datasets/hand_segmented_features'
city_overwrite = true
tile_overwrite = true
